# Generated by Django 5.1.7 on 2025-03-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author_language_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='No summary available', help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
